const express = require('express')
const path = require('path')
const cors = require('cors')
const bodyParser = require('body-parser')
// const {logger} = require('./middlewares/index')
const app = express()

// app.use(bodyParser.json())
// app.use(bodyParser.urlencoded({extended: true}))
app.use(express.urlencoded({ extended: false }))
app.set('view engine', 'ejs')
app.set('views', path.join(__dirname, 'views'))
app.use(express.static(path.join(__dirname, 'static')))
app.use(cors())
app.use(express.json())
// app.use(logger)

const mainRouter = require('./routes/main')
const signUp_signIn = require('./routes/signUp_signIn')
const noti = require('./routes/email_Noti')
const home = require('./routes/home')
const forgot = require('./routes/forgotpass')
const profile = require('./routes/profile')

app.use(mainRouter.router)
app.use(signUp_signIn.router)
app.use(noti.router)
app.use(home.router)
app.use(forgot.router)
app.use(profile.router)

app.listen(3000, () => console.log("Server is running..."))